workflows:
  ios-workflow:
    name: iOS Build
    environment:
      node: latest
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build React App
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
    artifacts:
      - ios/App/App.xcodeproj
    publishing:
      email:
        recipients:
          - babykeeper.bordais@gmail.com # Mets ton email ici